<?php

/**
 * @file
 * Contains module nmma_boat_finder_embed.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\nmma_boat_finder_embed\BoatFinderEmbedLibraryAlter;
use Drupal\nmma_boat_finder_embed\BoatFinderEmbedPreprocessor;

/**
 * @file
 * Contains nmma_boat_finder_embed.module.
 */

/**
 * Implements hook_help().
 */
function nmma_boat_finder_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nmma_boat_finder_embed module.
    case 'help.page.nmma_boat_finder_embed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Module to embed the NMMA Boat Finder Application') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nmma_boat_finder_embed_theme() {
  return [
    'boat_finder_embed' => [
      'render element' => 'element',
      'variables' => [
        'show_id' => 'dbcom',
        'boat_type' => NULL,
        'boat_brand' => NULL,
        'paged' => FALSE,
        'show_booth_info' => FALSE,
        'show_exhibitor_info' => FALSE,
        'max_length' => NULL,
        'max_price' => NULL,
        'show_color' => NULL,
        'modal_sponsor_tagline' => NULL,
        'modal_sponsor_image' => NULL,
        'modal_sponsor_link' => NULL,
        'rows_between_sponsor_cards' => NULL,
        'sponsor_card_link' => NULL,
        'sponsor_card_image' => NULL,
        'city_location' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_views_view_field().
 *
 * This function modifies the output of a specific field within a Views display.
 * It targets the 'boatfinder_views' view and the 'name' field that has a
 * relationship to the 'field_brand_boat_type_taxonomy_term_field_data' field.
 * If those conditions are met, it delegates further processing to the
 * BoatFinderEmbedPreprocessor class to alter the row output, such as appending
 * custom links for filtering boats by brand and type.
 */
function nmma_boat_finder_embed_preprocess_views_view_field(array &$variables): void {
  if ($variables['view']->storage->id() == 'boatfinder_views' && $variables['field']->field == 'name' && $variables['field']->relationship == 'field_brand_boat_type_taxonomy_term_field_data') {
    \Drupal::classResolver(BoatFinderEmbedPreprocessor::class)->alterBoatBrandAndTypeRow($variables);
  }
}

/**
 * Implements hook_library_info_alter().
 *
 * Alters the library definitions for the 'boat_finder_embed' library
 * provided by the 'nmma_boat_finder' module. This allows for dynamic
 * modifications of the library's properties or dependencies before
 * they are included in the page.
 *
 * @see hook_library_info_alter()
 * @see \Drupal\nmma_boat_finder_embed\BoatFinderEmbedLibraryAlter::libraryInfoAlter()
 */
function nmma_boat_finder_embed_library_info_alter(array &$libraries, $extension): void {
  // Check if the library we're altering is the boat_finder_embed library.
  if ($extension === 'nmma_boat_finder_embed' && isset($libraries['boat_finder_embed'])) {
    // Delegate the library alteration to the BoatFinderEmbedLibraryAlter class.
    \Drupal::classResolver(BoatFinderEmbedLibraryAlter::class)->libraryInfoAlter($libraries, $extension);
  }
}

/**
 * Implements hook_css_alter().
 *
 * Alters the css to change group for boat_finder_embed css.
 * As by default Drupal sets CSS_AGGREGATE_DEFAULT for
 * non-theme css files. This is needed so boat_finder_embed library css
 * is ordered correctly.
 *
 * @see \Drupal\Core\Asset\AssetResolver::getCssAssets()
 * @see \Drupal\nmma_boat_finder_embed\BoatFinderEmbedLibraryAlter::cssAlter()
 */
function nmma_boat_finder_embed_css_alter(&$css, AttachedAssetsInterface $assets, LanguageInterface $language): void {
  \Drupal::classResolver(BoatFinderEmbedLibraryAlter::class)->cssAlter($css);
}
